__title__ = 'typish'
__version__ = '1.6.0'
__author__ = 'Ramon Hagenaars'
__author_email__ = 'ramon.hagenaars@gmail.com'
__description__ = 'Functionality for types'
__url__ = 'https://github.com/ramonhagenaars/typish'
__license__ = 'MIT'
